[toolchain]
package_manager = "yarn"

[features]
seeds = false
skip-lint = false

[programs.devnet]
d_storage_app = "Ed5i4GsQCTU5NLvgieHUWHFAGfBJ61NfktWw271fesEJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
