[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flexible_token_exchange = "CZEiX9NY3idiU3AFdafekgEkvH31W8ZF5P8sC8tHwC4v"

[programs.devnet]
flexible_token_exchange = "HWHCbmSEp3V56MM7oVGYmdVLaFupSUUr9kpbfj2zAAuq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
url = "https://rpc.ankr.com/solana_devnet"
wallet = "./bosj4sevzHejo3ueZnSa7gdm1D44WCRD54kJZPYf3RX.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
